apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: replicasetscalers.kopf.dev
spec:
  scope: Namespaced
  group: kopf.dev
  names:
    kind: ReplicasetScaler
    plural: replicasetscalers
    singular: replicasetscaler
    shortNames:
      - rss
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                schedules:
                  type: array
                  items:
                    type: object
                    properties:
                      replicasetname:
                        type: string
                      namespace:
                        type: string
                      scaleup:
                        type: object
                        properties:
                          schedule:
                            type: string
                            pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
                          replicas:
                            type: integer
                          label:
                            type: string  
                      scaledown:
                        type: object
                        properties:
                          schedule:
                            type: string
                            pattern: '^(\d+|\*)(/\d+)?(\s+(\d+|\*)(/\d+)?){4}$'
                          replicas:
                            type: integer      
                          label:
                            type: string            