apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: backend-application
  namespace: backend
  labels:
    app: guestbook
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: backend
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: php-redis
        image: gcr.io/google_samples/gb-frontend:v3
